import type { Product, Category, Review, Avatar } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const img = PlaceHolderImages.find((p) => p.id === id);
  return img ? { url: img.imageUrl, hint: img.imageHint } : { url: 'https://placehold.co/600x400', hint: 'placeholder' };
};

export const products: Product[] = [
  {
    id: '1',
    slug: 'elegant-white-summer-dress',
    name: 'Elegant White Summer Dress',
    description: 'A light and airy dress perfect for summer.',
    longDescription: 'Made from 100% organic cotton, this dress features a flattering A-line cut and delicate lace details. Perfect for beach walks or brunch with friends. Easy to care for and breathable.',
    images: [getImage('prod-1').url],
    imageHints: [getImage('prod-1').hint],
    price: 79.99,
    category: 'clothing',
    tags: ['summer', 'dress', 'white'],
    variants: [
      { id: '1-s', color: '#FFFFFF', colorName: 'White', size: 'S', stock: 15 },
      { id: '1-m', color: '#FFFFFF', colorName: 'White', size: 'M', stock: 10 },
      { id: '1-l', color: '#FFFFFF', colorName: 'White', size: 'L', stock: 5 },
    ],
    rating: 4.8,
    reviewCount: 25,
  },
  {
    id: '2',
    slug: 'classic-black-leather-jacket',
    name: 'Classic Black Leather Jacket',
    description: 'A timeless wardrobe staple.',
    longDescription: 'Crafted from premium full-grain leather, this jacket offers a sleek silhouette and durable construction. Features asymmetrical zip, multiple pockets, and a comfortable inner lining.',
    images: [getImage('prod-2').url],
    imageHints: [getImage('prod-2').hint],
    price: 249.99,
    category: 'clothing',
    tags: ['jacket', 'leather', 'black'],
    variants: [
      { id: '2-m', color: '#000000', colorName: 'Black', size: 'M', stock: 8 },
      { id: '2-l', color: '#000000', colorName: 'Black', size: 'L', stock: 12 },
      { id: '2-xl', color: '#000000', colorName: 'Black', size: 'XL', stock: 7 },
    ],
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: '7',
    slug: 'white-leather-sneakers',
    name: 'White Leather Sneakers',
    description: 'Versatile and comfortable for everyday wear.',
    longDescription: 'Minimalist design meets maximum comfort. These sneakers feature a supple leather upper, cushioned insole, and a durable rubber outsole. Pairs perfectly with jeans, shorts, or dresses.',
    images: [getImage('prod-7').url],
    imageHints: [getImage('prod-7').hint],
    price: 119.99,
    category: 'shoes',
    tags: ['sneakers', 'white', 'leather'],
    variants: [
      { id: '7-39', color: '#FFFFFF', colorName: 'White', size: '39', stock: 20 },
      { id: '7-40', color: '#FFFFFF', colorName: 'White', size: '40', stock: 18 },
      { id: '7-41', color: '#FFFFFF', colorName: 'White', size: '41', stock: 15 },
      { id: '7-42', color: '#FFFFFF', colorName: 'White', size: '42', stock: 12 },
    ],
    rating: 4.7,
    reviewCount: 58,
  },
  {
    id: '11',
    slug: 'gold-analog-watch',
    name: 'Gold Analog Watch',
    description: 'An elegant timepiece with a classic design.',
    longDescription: 'This watch boasts a stainless steel case with a gold finish, a minimalist white dial, and a genuine leather strap. Water-resistant up to 50 meters, it combines style with functionality.',
    images: [getImage('prod-11').url],
    imageHints: [getImage('prod-11').hint],
    price: 189.99,
    category: 'accessories',
    tags: ['watch', 'gold', 'accessory'],
    variants: [
      { id: '11-std', color: '#FFD700', colorName: 'Gold', size: 'One Size', stock: 25 },
    ],
    rating: 4.9,
    reviewCount: 33,
  },
  {
    id: '15',
    slug: 'wireless-over-ear-headphones',
    name: 'Wireless Over-Ear Headphones',
    description: 'Immersive sound experience in a sleek package.',
    longDescription: 'Enjoy crystal-clear audio with these noise-cancelling headphones. Up to 30 hours of battery life, comfortable ear cups for all-day wear, and seamless Bluetooth 5.0 connectivity.',
    images: [getImage('prod-15').url],
    imageHints: [getImage('prod-15').hint],
    price: 199.99,
    category: 'tech-style',
    tags: ['headphones', 'tech', 'black'],
    variants: [
      { id: '15-std-black', color: '#000000', colorName: 'Black', size: 'One Size', stock: 30 },
      { id: '15-std-white', color: '#FFFFFF', colorName: 'White', size: 'One Size', stock: 22 },
    ],
    rating: 4.8,
    reviewCount: 61,
  },
  // Add more products to reach 12-24
  {
    id: '3',
    slug: 'blue-denim-jeans',
    name: 'Blue Denim Jeans',
    description: 'Comfortable and stylish slim-fit jeans.',
    longDescription: 'A modern take on a classic. Made with stretch denim for all-day comfort, these jeans feature a slim fit and a classic five-pocket design.',
    images: [getImage('prod-3').url],
    imageHints: [getImage('prod-3').hint],
    price: 89.99,
    category: 'clothing',
    tags: ['jeans', 'denim', 'blue'],
    variants: [
      { id: '3-30', color: '#3b82f6', colorName: 'Blue', size: '30/32', stock: 14 },
      { id: '3-32', color: '#3b82f6', colorName: 'Blue', size: '32/32', stock: 20 },
      { id: '3-34', color: '#3b82f6', colorName: 'Blue', size: '34/32', stock: 11 },
    ],
    rating: 4.6,
    reviewCount: 34,
  },
  {
    id: '8',
    slug: 'brown-leather-boots',
    name: 'Brown Leather Boots',
    description: 'Rugged yet refined, perfect for any occasion.',
    longDescription: 'Handcrafted from genuine leather, these boots are built to last. With a durable sole and comfortable fit, they are as practical as they are stylish.',
    images: [getImage('prod-8').url],
    imageHints: [getImage('prod-8').hint],
    price: 179.99,
    category: 'shoes',
    tags: ['boots', 'leather', 'brown'],
    variants: [
      { id: '8-41', color: '#854d0e', colorName: 'Brown', size: '41', stock: 10 },
      { id: '8-42', color: '#854d0e', colorName: 'Brown', size: '42', stock: 15 },
      { id: '8-43', color: '#854d0e', colorName: 'Brown', size: '43', stock: 9 },
    ],
    rating: 4.8,
    reviewCount: 45,
  },
  {
    id: '12',
    slug: 'black-leather-handbag',
    name: 'Black Leather Handbag',
    description: 'A chic and spacious bag for your essentials.',
    longDescription: 'Made from soft, genuine leather, this handbag features multiple compartments to keep you organized. Its timeless design complements any outfit.',
    images: [getImage('prod-12').url],
    imageHints: [getImage('prod-12').hint],
    price: 149.99,
    category: 'accessories',
    tags: ['handbag', 'leather', 'black'],
    variants: [
      { id: '12-std', color: '#000000', colorName: 'Black', size: 'One Size', stock: 18 },
    ],
    rating: 4.9,
    reviewCount: 28,
  },
    {
    id: '16',
    slug: 'sleek-white-earbuds',
    name: 'Sleek White Earbuds',
    description: 'Compact, stylish, with high-fidelity sound.',
    longDescription: 'Experience true wireless freedom. These earbuds offer a secure fit, intuitive touch controls, and come with a compact charging case that provides up to 24 hours of total listening time.',
    images: [getImage('prod-16').url],
    imageHints: [getImage('prod-16').hint],
    price: 99.99,
    category: 'tech-style',
    tags: ['earbuds', 'tech', 'white'],
    variants: [
      { id: '16-std', color: '#FFFFFF', colorName: 'White', size: 'One Size', stock: 40 },
    ],
    rating: 4.7,
    reviewCount: 75,
  },
  {
    id: '4',
    slug: 'slim-fit-gray-t-shirt',
    name: 'Slim Fit Gray T-Shirt',
    description: 'A versatile basic for any wardrobe.',
    longDescription: 'Made from a soft cotton blend, this t-shirt offers a comfortable, slim fit. An essential piece that can be dressed up or down.',
    images: [getImage('prod-4').url],
    imageHints: [getImage('prod-4').hint],
    price: 29.99,
    category: 'clothing',
    tags: ['tshirt', 'gray', 'basic'],
    variants: [
      { id: '4-s', color: '#9ca3af', colorName: 'Gray', size: 'S', stock: 30 },
      { id: '4-m', color: '#9ca3af', colorName: 'Gray', size: 'M', stock: 25 },
      { id: '4-l', color: '#9ca3af', colorName: 'Gray', size: 'L', stock: 20 },
    ],
    rating: 4.5,
    reviewCount: 19,
  },
   {
    id: '9',
    slug: 'black-high-heels',
    name: 'Black High Heels',
    description: 'Elegant and classic pointed-toe pumps.',
    longDescription: 'Step out in style with these classic high heels. A pointed toe and stiletto heel create a timeless silhouette. Perfect for formal events or a night out.',
    images: [getImage('prod-9').url],
    imageHints: [getImage('prod-9').hint],
    price: 129.99,
    category: 'shoes',
    tags: ['heels', 'black', 'formal'],
    variants: [
      { id: '9-38', color: '#000000', colorName: 'Black', size: '38', stock: 11 },
      { id: '9-39', color: '#000000', colorName: 'Black', size: '39', stock: 13 },
      { id: '9-40', color: '#000000', colorName: 'Black', size: '40', stock: 8 },
    ],
    rating: 4.7,
    reviewCount: 31,
  },
   {
    id: '13',
    slug: 'stylish-sunglasses',
    name: 'Stylish Sunglasses',
    description: 'Protect your eyes with these fashionable shades.',
    longDescription: 'These sunglasses feature a modern frame and provide 100% UV protection. Lightweight and comfortable for all-day wear.',
    images: [getImage('prod-13').url],
    imageHints: [getImage('prod-13').hint],
    price: 59.99,
    category: 'accessories',
    tags: ['sunglasses', 'accessory', 'unisex'],
    variants: [
      { id: '13-std', color: '#000000', colorName: 'Black', size: 'One Size', stock: 35 },
    ],
    rating: 4.6,
    reviewCount: 22,
  }
];

export const categories: Category[] = [
  { id: 'clothing', name: 'Clothing', imageUrl: getImage('cat-clothes').url, imageHint: getImage('cat-clothes').hint },
  { id: 'shoes', name: 'Shoes', imageUrl: getImage('cat-shoes').url, imageHint: getImage('cat-shoes').hint },
  { id: 'accessories', name: 'Accessories', imageUrl: getImage('cat-accessories').url, imageHint: getImage('cat-accessories').hint },
  { id: 'tech-style', name: 'Tech', imageUrl: getImage('cat-tech').url, imageHint: getImage('cat-tech').hint },
];

export const reviews: Review[] = [
  {
    id: '1',
    productId: '1',
    author: 'Sophie L.',
    avatarUrl: getImage('review-avatar-1').url,
    rating: 5,
    text: 'This dress is absolutely beautiful! The fabric is so light and comfortable, perfect for the climate here. I received so many compliments.',
    date: '2023-08-15',
  },
  {
    id: '2',
    productId: '2',
    author: 'Marc-Antoine P.',
    avatarUrl: getImage('review-avatar-2').url,
    rating: 5,
    text: 'The quality of this leather jacket is insane. It feels and looks so premium. Worth every penny. A true classic for my wardrobe.',
    date: '2023-09-01',
  },
  {
    id: '3',
    productId: '7',
    author: 'Jessica B.',
    avatarUrl: getImage('review-avatar-3').url,
    rating: 4,
    text: 'Really love these sneakers. They are very comfortable for walking around all day. They got a little dirty quickly, but that\'s expected with white shoes.',
    date: '2023-08-22',
  },
];

export const avatars: Avatar[] = [
  { id: 'avatar-1', description: 'Slender build, female', imageUrl: getImage('avatar-1').url, imageHint: getImage('avatar-1').hint },
  { id: 'avatar-2', description: 'Athletic build, male', imageUrl: getImage('avatar-2').url, imageHint: getImage('avatar-2').hint },
  { id: 'avatar-3', description: 'Curvy build, female', imageUrl: getImage('avatar-3').url, imageHint: getImage('avatar-3').hint },
  { id: 'avatar-4', description: 'Broad build, male', imageUrl: getImage('avatar-4').hint, imageHint: getImage('avatar-4').hint },
];
